### ISSUE TITLE
Token validation bug

### ISSUE THREAD

**Issue by jacksctsai** [findhit/token-generator#3]
I think the following code has a bug. A token should be invalid if it has a timestamp before current time.

```
            // Check if timestamp is expired
            if ( timestamp > currentTimestamp() + this.options.expiresOn ) {
                throw new Error( "token is expired" );
            }
```

https://github.com/findhit/token-generator/blob/master/index.js#L179

**Comment by cusspvz** [comment]
A token should be invalidated if it is higher than the currentTimestamp plus the expiration date.
I think it is working, and it is being covered by [some basic tests](https://github.com/findhit/token-generator/blob/master/test/basic.test.js).

If you are experiencing troubles please feel free to provide me a test unit where you could reproduce the issue.

Closing this till further notice.
