### ISSUE TITLE
How to destroy token?

### ISSUE THREAD

**Issue by AlfAinTech** [findhit/token-generator#4]
I have generated the token for user authentication but can't figure out how to destroy it on logout request.

**Comment by cusspvz** [comment]
This is a generator. If you want to provide some revoke functionality to them, you'll have to save all the generated tokens and then revoke them manually and add the respective conditional to your system. Or, you can introduce smaller timeframes, such as 5min to each token.

**Comment by cusspvz** [comment]
Please let me know if you have any other questions
